dist: xenial

language: python
python:
  - "3.8"

addons:
  chrome: stable

before_install:
  - wget -N 
  - http://chromedriver.storage.googleapis.com
      /83.0.4103.39/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver 
    /usr/local/bin/chromedriver
  - sleep 3
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

services:
  - postgresql
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
        - sudo apt-get install -qq libjpeg8-dev libfreetype6-dev libwebp-dev
        - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
        - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
        - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm

      language: python
      python:
        - "3.8"
      install:
        - pip install -r requirements/local.txt
      script:
        - "pytest"
