dist: xenial

language: python
python:
  - "3.8"

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest

before_install:
  - sudo apt-get update
  - sudo apt-get install dbus-x11
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin

services:
  - postgresql

jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
        - sudo apt-get install -qq libjpeg8-dev libfreetype6-dev libwebp-dev
        - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
        - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
        - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm

      language: python
      python:
        - "3.8"
      install:
        - pip install -r requirements/local.txt
      script:
        - "pytest"
