# Generated by Django 2.2.12 on 2020-06-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="club",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="club.Club"
            ),
            preserve_default=False,
        ),
    ]
