# Generated by Django 3.0.7 on 2020-07-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_award_memberaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Award'),
        ),
    ]
