# Generated by Django 3.0.7 on 2020-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20200704_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
